[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = "lts"
nodejs = "lts"
python = "latest"
ruby = "latest"
terraform = "latest"

"aqua:golangci/golangci-lint" = "latest"

usage = "latest" # used for mise completions

[settings]
idiomatic_version_file_enable_tools = ["ruby", "python", "node"]
